const ALERT_SHOW_TIME = 5000;
const URL = 'https://26.javascript.pages.academy/kekstagram';
const COMMENTS_STEP = 5;
const MIN_HASHTAG_LENGTH = 2;
const MAX_COMMENT_LENGTH = 140;
const MAX_HASHTAGS_AMOUNT = 5;
const ZOOM_STEP = 25;

export {
  ALERT_SHOW_TIME,
  URL,
  COMMENTS_STEP,
  MIN_HASHTAG_LENGTH,
  MAX_COMMENT_LENGTH,
  MAX_HASHTAGS_AMOUNT,
  ZOOM_STEP
};
